### ISSUE TITLE
do not enforce removal of `/etc/apt/sources.list`

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#11]
```
"{{ slsdotpath }}-remove-debian-default-sources.list":
  file.absent:
    - require:
      - pkg: "{{ slsdotpath }}-installed"
    - name: /etc/apt/sources.list
 ```

Deletion of `/etc/apt/sources.list` makes sense when building Kicksecure while a default Debian sources list has been used but this should not be enforced going forward.

The user should be free to use `/etc/apt/sources.list` with custom repositories without having that file surprisingly deleted. That should be a "do once" action only.

And also only be removed if the user did not previously customized it to avoid data loss (loss of repositories).
