### ISSUE TITLE
upstream Qubes VM kernel 

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#3]
https://github.com/ben-grande/qusal/blob/main/salt/kicksecure-minimal/install.sls

```
"{{ slsdotpath }}-installed":
  pkg.installed:
    - refresh: True
    - install_recommends: False
    - skip_suggestions: True
    - pkgs:
      - kicksecure-qubes-cli
      - lkrg-dkms
      - hardened-kernel
      - tirdad
      - linux-image-amd64
      - linux-headers-amd64
      - grub2
      - qubes-kernel-vm-support
```

Installing 

      - linux-image-amd64
      - linux-headers-amd64
      - grub2
      - qubes-kernel-vm-support

should not be up to Kicksecure. Basically I am suggesting to contribute towards https://github.com/QubesOS/qubes-issues/issues/5212.

This is problematic because it derivatives from Kicksecure default kernel, which is Qubes default kernel configuration.

This is unmaintainable, because if there are Qubes VM kernel specific crashes, issues, then these would be reported by users to Kicksecure where I would have no possibility to debug these except saying "please reproduce this in Qubes Debian and report the bug to Qubes".

1) Add a PR for https://github.com/QubesOS/qubes-meta-packages to add a meta package pulling all of these dependencies.

2) Add a PR for Qubes Debian Template builder installing the kernel packages by default.

3) Other changes towards making "flipping the switch to VM kernel" more easy. Last PR would be actually changing the default.

Don't be discouraged by https://github.com/QubesOS/qubes-doc/pull/1342 not being merged for a long time. That apparently depends on Qubes internal processes, maintainer availability. It's easier to land Qubes source code pull requests than Qubes documentation pull requests.
